chore: restore checks

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -4,17 +4,17 @@ set -euo pipefail
 
 # Based on: https://github.com/luizm/asdf-shellcheck/blob/master/bin/install
 
-# ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
+ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
 
-# test -n "$ASDF_INSTALL_VERSION" || {
-#   echo 'Missing ASDF_INSTALL_VERSION'
-#   exit 1
-# }
+test -n "$ASDF_INSTALL_VERSION" || {
+  echo 'Missing ASDF_INSTALL_VERSION'
+  exit 1
+}
 
-# test -n "$ASDF_INSTALL_PATH" || {
-#   echo 'Missing ASDF_INSTALL_PATH'
-#   exit 1
-# }
+test -n "$ASDF_INSTALL_PATH" || {
+  echo 'Missing ASDF_INSTALL_PATH'
+  exit 1
+}
 
 _get_arch() {
   local arch
